In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


**Tensor**

Scalar

In [3]:
scalar  = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

**Vector**

In [6]:
vector = torch.tensor([7,7])

In [7]:
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
Matrix = torch.tensor([[7,9],
                       [9,10]])
Matrix

tensor([[ 7,  9],
        [ 9, 10]])

In [10]:
Matrix.ndim

2

In [11]:
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [12]:
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random tensor

**In rand or other fucntion like zeros and ones we basicly put thier the shape of tensor than as a paramiter than these fuction return ous the tensor**

In [16]:
random = torch.rand(1,10,10)
random

tensor([[[0.0436, 0.8793, 0.2955, 0.2778, 0.3139, 0.2026, 0.4540, 0.0280,
          0.3484, 0.6621],
         [0.8760, 0.3858, 0.0677, 0.3732, 0.6574, 0.8252, 0.3341, 0.3124,
          0.9470, 0.8698],
         [0.0057, 0.0104, 0.8802, 0.0090, 0.9850, 0.5333, 0.2518, 0.4526,
          0.5885, 0.1804],
         [0.8501, 0.3844, 0.3222, 0.1521, 0.7409, 0.9025, 0.4397, 0.3250,
          0.3045, 0.5216],
         [0.4778, 0.1483, 0.2092, 0.1026, 0.1386, 0.0276, 0.4733, 0.5339,
          0.4169, 0.6973],
         [0.3052, 0.9310, 0.4564, 0.0990, 0.1615, 0.2888, 0.9519, 0.6030,
          0.3437, 0.9485],
         [0.7246, 0.1405, 0.1059, 0.9397, 0.2022, 0.9837, 0.8916, 0.0135,
          0.5679, 0.1343],
         [0.7839, 0.4968, 0.8643, 0.8280, 0.2249, 0.6317, 0.2147, 0.2517,
          0.2016, 0.3862],
         [0.0582, 0.3973, 0.3721, 0.4508, 0.3801, 0.1255, 0.6046, 0.2029,
          0.9545, 0.0557],
         [0.5264, 0.2011, 0.3154, 0.3301, 0.8146, 0.3444, 0.8114, 0.5890,
          0.4079,

In [17]:

random.ndim

3

In [18]:
random.shape

torch.Size([1, 10, 10])

In [19]:
random_img = torch.rand(size=(224,244,3))
random_img.shape 

torch.Size([224, 244, 3])

In [20]:
random.ndim

3

In [21]:
torch.rand(size=(4,5))

tensor([[0.2239, 0.4206, 0.6125, 0.2693, 0.8754],
        [0.5292, 0.7667, 0.3100, 0.1250, 0.2684],
        [0.2741, 0.9854, 0.1766, 0.6905, 0.3742],
        [0.0369, 0.0917, 0.6884, 0.5526, 0.1138]])

In [22]:
 zero = torch.zeros(size=(3,4))
 z = torch.zeros([3,4])

In [23]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones = torch.ones([6,7])
ones

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
torch.arange(22,33)

tensor([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [28]:
step = torch.arange(start=1,end=1000000,step=400)
step

tensor([     1,    401,    801,  ..., 998801, 999201, 999601])

In [29]:
tensor_like = torch.zeros_like(input=step)

In [30]:
tensor_like

tensor([0, 0, 0,  ..., 0, 0, 0])

# Tensor Dtype:

**Tensor dtype is one of 3 big erorr i will face in deep learning**


**1. Tensors not right datatype**

**2. Tensors not right shape**

**3. Tensor not on the right device**

In [31]:
float_32_dtype = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # whats datatype is the tensor [e.g. float32 or float16]
                              device=None, # what device in your tensor on
                              requires_grad=False) # whather or not  to track gradients with this tensor operation
float_32_dtype

tensor([3., 6., 9.])

In [32]:
float_32_dtype.dtype

torch.float32

In [33]:
float_16_dtype = float_32_dtype.type(torch.float16)
float_16_dtype

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_dtype.dtype

torch.float16

In [35]:
float_16_dtype * float_32_dtype

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [37]:
float_32_dtype * int_32_tensor

tensor([ 9., 36., 81.])

# Create some tensor

In [38]:
some_tensor = torch.rand(6,7)



In [39]:
some_tensor

tensor([[0.2668, 0.3907, 0.2227, 0.0133, 0.2223, 0.5544, 0.9566],
        [0.5873, 0.4969, 0.3020, 0.1856, 0.1629, 0.7095, 0.4710],
        [0.1410, 0.2190, 0.7928, 0.4261, 0.5015, 0.3926, 0.2530],
        [0.5373, 0.9353, 0.6010, 0.7856, 0.1952, 0.0606, 0.0879],
        [0.8051, 0.9852, 0.9588, 0.7604, 0.8645, 0.2751, 0.0979],
        [0.5100, 0.8411, 0.9376, 0.2350, 0.9694, 0.8154, 0.0690]])

In [40]:
print(some_tensor)
print(f'Datatype of tensor:{some_tensor.dtype}')
print(f'Shape of tensor :{some_tensor.shape}')
print(f'Device of tensor is on:{some_tensor.device}')



tensor([[0.2668, 0.3907, 0.2227, 0.0133, 0.2223, 0.5544, 0.9566],
        [0.5873, 0.4969, 0.3020, 0.1856, 0.1629, 0.7095, 0.4710],
        [0.1410, 0.2190, 0.7928, 0.4261, 0.5015, 0.3926, 0.2530],
        [0.5373, 0.9353, 0.6010, 0.7856, 0.1952, 0.0606, 0.0879],
        [0.8051, 0.9852, 0.9588, 0.7604, 0.8645, 0.2751, 0.0979],
        [0.5100, 0.8411, 0.9376, 0.2350, 0.9694, 0.8154, 0.0690]])
Datatype of tensor:torch.float32
Shape of tensor :torch.Size([6, 7])
Device of tensor is on:cpu


In [41]:
!cat /proc/cpuinfo | grep 'model name'


model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz


In [42]:
!free -h


              total        used        free      shared  buff/cache   available
Mem:           12Gi       908Mi       8.2Gi       1.0Mi       3.6Gi        11Gi
Swap:            0B          0B          0B


# Maniputating Tensors (tensor operation)
**Tensor operation Include:**



1.   Addition
2.   Subtraction
3.   Multipication(element-wise)
4.   Divition
5.   Matrix multipication



In [43]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [44]:
# multiplay tensor
tensor * 10

tensor([10, 20, 30])

In [45]:
# subtract
tensor - 10

tensor([-9, -8, -7])

# Pytorch fuction

In [46]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [48]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

# Matrix multiplication
**Tow main ways of performing multiplication**



1.   Element-wise multipication
2.   Matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy:

1. The inner dimensions must match:



*   (3,2) @ (3,2) won't work
*   (2,3) @ (3,2) will work
*   (3,2) @ (2,3) will work

2. The resulting  matrix has the shape of the outer dimensions:

* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)




In [49]:
torch.matmul(tensor,tensor)

tensor(14)

In [50]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.08 ms, sys: 11 µs, total: 1.09 ms
Wall time: 937 µs


In [51]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 27 µs, sys: 5 µs, total: 32 µs
Wall time: 35.8 µs


tensor(14)

**Inner Dimentions**

In [52]:
torch.matmul(torch.rand(4,6),torch.rand(6,4))

tensor([[1.6979, 0.9110, 1.6257, 0.6519],
        [1.0816, 0.4270, 1.1573, 0.3167],
        [2.3863, 1.4887, 2.2756, 1.5427],
        [1.1815, 0.4814, 1.3333, 0.4691]])

# One of the most common erros in deep learning : Shape errors

In [53]:

# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])


In [55]:
torch.matmul(tensor_A,tensor_B)

RuntimeError: ignored

In [56]:
tensor_B.shape ,tensor_A.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues we can manipulate the shape of one of our tensors using a ''transpose''
A transpose switches the axes or dimensions of a given tensor 

# Transpose means coverting columns to rows or rows to columns

In [57]:
tensor_B.T,          tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [58]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [59]:
tensor_B.T.shape

torch.Size([2, 3])

In [60]:
tensor_B.shape

torch.Size([3, 2])

**After fixing matric maltiplication**

In [61]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [62]:
print(f'Original shapes: tensor_A ={tensor_A.shape}, tensor_B={tensor_B.shape}')
print(f"Make New shapes of a tensor: tensor_A = {tensor_A.shape}, tensor_B.Transpose={tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A =torch.Size([3, 2]), tensor_B=torch.Size([3, 2])
Make New shapes of a tensor: tensor_A = torch.Size([3, 2]), tensor_B.Transpose=tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Finding the min,max , mean, sum,etc(tensor aggregation)

In [63]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
torch.min(x)

tensor(0)

In [65]:
torch.max(x)

tensor(90)

In [66]:
torch.mean(x.type(torch.float64)), x.type(torch.float64).mean()

(tensor(45., dtype=torch.float64), tensor(45., dtype=torch.float64))

In [67]:
# sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [68]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
# find the position in the tensor that has the minium value with argmin() -> returns index position of targt tensor where the minimum value occurs
x.argmin()

tensor(0)

In [70]:
# FInd the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [71]:
x[9]

tensor(90)

#Reahaping , Stacking, aqueezing and unsqueezing tensor


*   Reshaping - reshapes an input tensor to defined shape
*   View - Resurn a view of an input of certrain shape but keep the same memory as the original tensor


*   Stacking = combine mutiple tensors on top of each other or side by side
*   Squeeze - removes all 1 dimensions from  a tensor


*   Unsqueeze - add a 1 dimension to  a terget tensor
*   Permute - Return a view of the input with dimensions permuted (swapped) in a certain way







In [72]:
tensor_x = torch.arange(1.,10.)
tensor_x, tensor_x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
# Adding extra dimensions
tensor_x_r = tensor_x.reshape(9,1)
tensor_x_r, tensor_x_r.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [74]:
# Change the view
z = tensor_x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
# changing z changes x [becasuse a view of a tensor shares the same memory as the original input]
z[:,0] = 5
z , tensor_x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [76]:
# stack tensore on top of each other
x_stacked = torch.stack([tensor_x,tensor_x,tensor_x,tensor_x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
tensor_x_r , tensor_x_r.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [78]:
# squeexe method basicly remove dimensions
tensor_x_r.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
tensor_x_r.squeeze().shape

torch.Size([9])

In [80]:
# torch.squeeze() - remove all single dimensions form a target tensor
print(f"Previous tensor:\n{tensor_x_r}")
print(f"Previous shape:{tensor_x_r.shape}")

# Remove extra dimensions from x reshaped
x_squeezed = tensor_x_r.squeeze()
print(f"\nNew Tensor:{x_squeezed}")
print(f"New shape:{x_squeezed.shape}")

Previous tensor:
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape:torch.Size([9, 1])

New Tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [81]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim ( dimesion)
print(f"Previous target:{x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")

Previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape:torch.Size([1, 9])


In [82]:
# torch.permute - rearrange the dimensions of a target tensor in specifiied order
x_original = torch.rand(size=(224,224,3)) # [height ,wedith,colour_channels]
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifs axis 0-> 1, 1->2,2->3
print(f"previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [83]:
x_original[0,0,0]  = 676912398723
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(6.7691e+11), tensor(6.7691e+11))

# Indexing (seleting data from tensors) 

# Slicing

In [84]:
## Indexing (selecting data from tensors)
x = torch.arange(1,10).reshape(1,3,3)
x ,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [85]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
x[0][1][1:2]

tensor([5])

In [87]:
x[0][0][0]

tensor(1)

In [88]:
x[0][2][2:3]

tensor([9])

In [89]:
# You can also use ':' to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [90]:
# Get all values of 0th and 1st dimensions but only index 1 of 2 dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [91]:
# Get all values of the o dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [92]:
# get 9
x[:,2,2]

tensor([9])

In [93]:
x[0,2,2]

tensor(9)

In [94]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [95]:
x[0,:,2]

tensor([3, 6, 9])



1.   # Nmpy to tensor 

2.   # Tensor to numpy



In [96]:
import numpy as np
import torch

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning : when converting from numpy-> pytorch,pytorch reflects numpys defaault datatype of float64 unless specified over wise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [97]:
# change the value of array , what will this do to 'tensor'?
array = array +1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [98]:
# tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [99]:
# change the tensor , what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducbility (trying to take random out of random)
In shot how a neural network learns:
start with random numbers-> tensor operations -> update random numbers to try and make them better representaions of the data->again->agin->again
To reduce the randommess in neural networks and Pytorch comes the concept of a random seed
Essentially what the random seed does is 'flavour' the randomness

In [100]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8699, 0.2445, 0.4734, 0.3449],
        [0.2210, 0.7211, 0.1499, 0.0068],
        [0.7361, 0.4824, 0.7762, 0.0347]])
tensor([[0.8878, 0.2601, 0.3195, 0.7226],
        [0.2238, 0.6262, 0.2296, 0.0281],
        [0.8461, 0.6457, 0.5472, 0.2807]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [101]:
# Let's make some random but reproducible tensors
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_C)
print(random_tensor_C ==random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


# Extrac resources for reproduciblility

https://pytorch.org/docs/stable/notes/randomness.html

# Check for GPU access with pytorch

In [102]:
torch.cuda.is_available()

True

In [103]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [104]:
# Count number of devices
torch.cuda.device_count()

1

In [106]:
## Putting tensors and models on the gpu
tensor = torch.tensor([1,2,3],device='cpu')
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [108]:
# Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [109]:
# of tensor is on GPU, can't tranform it to Numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [110]:
# to fix to gpu tensor with numpy issue we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu()

In [111]:
tensor_back_on_cpu.numpy()

array([1, 2, 3])