In [25]:
import torch

# create two matrices
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# compute the element-wise product of a and b
c = torch.einsum('ij,ij->ij', a, b)
print(c)

tensor([[ 5, 12],
        [21, 32]])


# permutation

In [16]:
x = torch.rand((2,3))
torch.einsum('ij->i',x)

tensor([0.7513, 2.2549])

In [19]:
x

tensor([[0.1256, 0.3446, 0.2811],
        [0.8036, 0.4699, 0.9814]])

# Sumation

In [18]:
torch.einsum('ij->',x)

tensor(3.0063)

# Columns Sum

In [20]:
torch.einsum('ij->j',x)

tensor([0.9293, 0.8145, 1.2625])

# Row Sum

In [21]:
torch.einsum('ij->i',x)

tensor([0.7513, 2.2549])

# Matrix - vactor Multipication

In [22]:
v = torch.rand(1,3)
v

tensor([[0.9035, 0.6947, 0.2231]])

In [23]:
torch.einsum('ij,kj->jk',x,v)

tensor([[0.8396],
        [0.5658],
        [0.2816]])

# Matrix Matrix Multipication

In [28]:
torch.einsum('ij,kj->ik',x,x)

tensor([[0.2135, 0.5387],
        [0.5387, 1.8298]])

# Dot product first row with first row of matrix

In [29]:
torch.einsum('i,i->',x[0],x[0])

tensor(0.2135)

# Hardwmard product (element -wise multipication)

In [32]:
torch.einsum('ij,ij->ij',a,b)

tensor([[ 5, 12],
        [21, 32]])

# Outer Product

In [36]:
a = torch.rand((3))
b = torch.rand((5))
torch.einsum("i,j->ij",a,b)

tensor([[0.5633, 0.3893, 0.5135, 0.2461, 0.0551],
        [0.4016, 0.2776, 0.3661, 0.1755, 0.0393],
        [0.2442, 0.1688, 0.2226, 0.1067, 0.0239]])

# Batch Matix Multipication

In [37]:
a = torch.rand((3,2,5))
b = torch.rand((3,5,3))
torch.einsum("ijk,ikl->ijl",a,b)

tensor([[[1.1345, 0.4373, 1.3538],
         [0.9558, 0.3618, 1.3580]],

        [[1.1885, 1.6214, 1.8640],
         [1.7487, 2.0753, 2.2489]],

        [[0.7315, 0.8350, 0.7993],
         [1.0149, 1.0675, 0.9840]]])

# Matix Diagonal

In [38]:
x = torch.rand((3,3))
torch.einsum('ii->i',x)

tensor([0.2741, 0.9359, 0.8498])

# Matix Trace

In [39]:
torch.einsum('ii->',x)

tensor(2.0597)

In [4]:
import torch

# create a 3D tensor with shape (batch_size, height, width)
x = torch.randn(2, 3, 4)

# permute the dimensions to obtain a tensor with shape (height, batch_size, width)
y = torch.einsum('bhw->hbw', x)


In [5]:
y

tensor([[[ 0.8026,  0.3564,  1.2165, -1.5074],
         [ 0.1897,  1.5893,  0.7320, -0.9231]],

        [[-0.6614,  0.6692, -0.6184,  0.6390],
         [-0.0061,  0.2947,  1.0751, -0.1674]],

        [[-0.7403, -1.4407, -1.1183,  0.0487],
         [-0.1383,  0.4907, -0.3737,  1.7388]]])

In [6]:
x

tensor([[[ 0.8026,  0.3564,  1.2165, -1.5074],
         [-0.6614,  0.6692, -0.6184,  0.6390],
         [-0.7403, -1.4407, -1.1183,  0.0487]],

        [[ 0.1897,  1.5893,  0.7320, -0.9231],
         [-0.0061,  0.2947,  1.0751, -0.1674],
         [-0.1383,  0.4907, -0.3737,  1.7388]]])